const classMapping = {
    'Entete'                : Entete,
    'DescriptionVoiture'    : DescriptionVoiture,
    'MenuConteneur'         : MenuConteneur,
    'FormulaireVoiture'     : FormulaireVoiture,
    'GestionMarque'         : GestionMarque,
    'GestionModele'         : GestionModele,
    'GestionCouleur'        : GestionCouleur,
    'GestionUsager'         : GestionUsager,
    'GestionVoiture'        : GestionVoiture,
    'GestionFacture'        : GestionFacture,
    'GestionTaxe'           : GestionTaxe,
    'ListeVoitures'         : ListeVoitures,
    'Paypal'                : Paypal,
    'VoirPlus'              : VoirPlus,
    'Voiture'               : Voiture,
    'GestionModele'         : GestionModele,
    'Filtre'                : Filtre,
    'FormulaireConnexion'   : FormulaireConnexion,
    'Chercher'              : Chercher,
    'Taxes'                 : Taxes,
    'Chercher'              : Chercher,
    'TraiterCommande'       : TraiterCommande,
    'CommandeVoiture'       : CommandeVoiture,
    'Succes'                : Succes
};