-- MySQL Script generated by MySQL Workbench
-- Wed Apr 14 14:36:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vehicules
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vehicules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vehicules` DEFAULT CHARACTER SET utf8 ;
USE `vehicules` ;

-- -----------------------------------------------------
-- Table `vehicules`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `permission` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `role`(`nom`, `permission`) VALUES ('gestionnaire', 'tous les privilèges');
INSERT INTO `role`(`nom`, `permission`) VALUES ('employé', 'Insertion, Modification, Suppression');
INSERT INTO `role`(`nom`, `permission`) VALUES ('client', 'Lecture et Insertion d\'une commande');
INSERT INTO `role`(`nom`, `permission`) VALUES ('inactif', 'Lecture et Insertion d\'une commande');

-- -----------------------------------------------------
-- Table `vehicules`.`usager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`usager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courriel` VARCHAR(45) UNIQUE NOT NULL,
  `motPasse` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `dateNaissance` DATE NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `codePostal` VARCHAR(6) NOT NULL,
  `idProvince` INT NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NULL,
  `telephoneCellulaire` VARCHAR(45) NOT NULL,
  `idLangue` INT NOT NULL,
  `idRole` INT NOT NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `idProvince`
    FOREIGN KEY (`idProvince`)
    REFERENCES `vehicules`.`province` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLangue`
    FOREIGN KEY (`idLangue`)
    REFERENCES `vehicules`.`langue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRole`
    FOREIGN KEY (`idRole`)
    REFERENCES `vehicules`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('yulia@gmail.com','1234','Merkulova','Yulia','2003-08-26','8480 rue Jean-Brillon','H8N2P6',12,'LaSalle','4384983850','4384983850',1,2);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('jean@gmail.com','1234','Senneville','Jean','1990-04-15','111 rue Lafontaine','H1N4K7',12,'Montréal','5145555555','5145555555',1,2);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('gloria@gmail.com','1234','Kiese','Gloria','2000-01-01','111 rue Lafontaine','H1N5T2',12,'Montreal','5145555555','5145555555',1,1);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('philippe@gmail.com','1234','Houle','Philippe','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('Paul@gmail.com','1234','Houle','Paul','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('john@gmail.com','1234','Houle','john','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('eureka@gmail.com','1234','Houle','eureka','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('bill@gmail.com','1234','Houle','bill','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('Sigourney@gmail.com','1234','Houle','Sigourney','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('roy@gmail.com','1234','Houle','roy','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('Linda@gmail.com','1234','Houle','Linda','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('robert@gmail.com','1234','Houle','robert','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('richard@gmail.com','1234','Houle','richard','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('kate@gmail.com','1234','Houle','kate','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('jerry@gmail.com','1234','Houle','jerry','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('picard@gmail.com','1234','Houle','picard','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('sisko@gmail.com','1234','Houle','sisko','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);
INSERT INTO `usager`(`courriel`, `motPasse`, `nom`, `prenom`, `dateNaissance`, `adresse`, `codePostal`, `idProvince`, `ville`, `telephone`, `telephoneCellulaire`, `idLangue`, `idRole`) VALUES ('dax@gmail.com','1234','Houle','dax','2024-12-12','72 Latour','j3n1l1',12,'Saint-Basile-le-Grand','5145555555','5145555555',1,3);

-- -----------------------------------------------------
-- Table `vehicules`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`pays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `pays`(`nom`) VALUES ('Canada');
INSERT INTO `pays`(`nom`) VALUES ('USA');

-- -----------------------------------------------------
-- Table `vehicules`.`langue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`langue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `langue`(`nom`, `code`) VALUES ('Français','fr-fr');
INSERT INTO `langue`(`nom`, `code`) VALUES ('English','en-gb');

-- -----------------------------------------------------
-- Table `vehicules`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idLangue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `idPays` INT NOT NULL,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idPays`)
  REFERENCES `vehicules`.`pays` (`id`),
  FOREIGN KEY (`idLangue`)
  REFERENCES `vehicules`.`langue` (`id`))
ENGINE = InnoDB;

INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (1,1,'Alberta',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (1,2,'Alberta',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (2,1,'Colombie-Britannique',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (2,2,'British Columbia',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (3,1,'Manitoba',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (3,2,'Manitoba',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (4,1,'Nouveau-Brunswick',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (4,2,'New Brunswick',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (5,1,'Nouvelle-Écosse',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (5,2,'Nova Scotia',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (6,1,'Terre-Neuve-et-Labrador',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (6,2,'Newfoundland and Labrador',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (7,1,'Territoires du Nord-Ouest',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (7,2,'Northwest Territories',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (8,1,'Nunavut',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (8,2,'Nunavut',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (9,1,'Ontario',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (9,2,'Ontario',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (10,1,'Île-du-Prince-Édouard',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (10,2,'Prince Edward Island',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (11,1,'Saskatchewan',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (11,2,'Saskatchewan',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (12,1,'Québec',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (12,2,'Quebec',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (13,1,'Yukon',1);
INSERT INTO `province`(`id`, `idLangue`, `nom`, `idPays`) VALUES (13,2,'Yukon',1);


-- -----------------------------------------------------
-- Table `vehicules`.`taxe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`taxe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `taux` DECIMAL(15,4) UNSIGNED NOT NULL,
  `idProvince` INT NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`idProvince`)
  REFERENCES `vehicules`.`province` (`id`))
ENGINE = InnoDB;

INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TPS',5,1,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVP',7,2,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TPS',5,2,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVP',7,3,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TPS',5,3,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVH',15,4,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVH',15,5,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVH',15,6,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TPS',5,7,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TPS',5,8,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVH',13,9,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVH',15,10,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TPS',5,12,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVQ',9.975,12,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TVP',6,11,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TPS',5,11,1);
INSERT INTO `taxe`(`nom`, `taux`, `idProvince`,`disponibilite`) VALUES ('TPS',5,13,1);

-- -----------------------------------------------------
-- Table `vehicules`.`journalConnexion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`journalConnexion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsager` INT,
  `date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `adresseIp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`idUsager`)
  REFERENCES `vehicules`.`usager` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `vehicules`.`motopropulseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`motopropulseur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
   `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO motopropulseur (nom) VALUES 
                    ('4x2'), ('4x4');

-- -----------------------------------------------------
-- Table `vehicules`.`annee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`annee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `annee` YEAR NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO annee (annee) VALUES
                    ('2010'), ('2011'), ('2012'), ('2013'), ('2014'), ('2015'), ('2016'), ('2017'), ('2018'), ('2019'), ('2020'), ('2021');

-- -----------------------------------------------------
-- Table `vehicules`.`marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`marque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO marque (nom) VALUES 
			('Chevrolet'), ('Ford'), ('Honda'), ('Hyundai'), ('Kia'), ('Mercedes'), ('Nissan'), ('Toyota'), ('Volkswagen'), ('Jeep'),
			('Dodge'), ('Mazda'), ('Ram'), ('GMC');        

-- -----------------------------------------------------
-- Table `vehicules`.`modele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`modele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `idMarque` INT NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `idMarque`
    FOREIGN KEY (`idMarque`)
    REFERENCES `vehicules`.`marque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO modele (nom, idMarque) VALUES
		('Cruze', 1), ('Focus', 2), ('Civic', 3), ('Forte', 5), ('Accent', 4), ('Elantra', 4), ('Micra', 7), ('Sentra', 7), ('Jetta', 9), 
		('Optima', 5), ('Benz-CLA250', 6), ('Versa_Note', 7), ('Compass', 10), ('Escape', 2), ('Rogue', 7), ('Journey', 11), 
		('Equinox', 1), ('CX-3', 12), ('Pathfinder', 7), ('Santa Fe', 4), ('CX-5', 12), ('Rav4', 8), ('Sedona', 5), ('Grand Caravan', 11), 
		('Odyssey', 3), ('Sienna', 8), ('Routan', 9), ('2500', 13), ('Ranger', 2), ('Gladiator', 10), ('3500', 13), ('Sierra 3500', 14), ('Canyon', 14);
					
-- -----------------------------------------------------
-- Table `vehicules`.`typeCarburant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`typeCarburant` (
  `id` INT NOT NULL,
  `idLangue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idLangue`)    REFERENCES `vehicules`.`langue` (`id`))
ENGINE = InnoDB;

 

INSERT INTO typeCarburant (id, idLangue, nom) VALUES
                    (1,1, 'Essence'), (1,2, 'Gasoline '), (2,1, 'Diesel'), (2,2, 'Diesel ');



-- -----------------------------------------------------
-- Table `vehicules`.`couleur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`couleur` (
  `id` INT NOT NULL,
  `idLangue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idLangue`)    REFERENCES `vehicules`.`langue` (`id`))
ENGINE = InnoDB;

 

INSERT INTO couleur (id, idLangue, nom) VALUES
                    (1, 1, 'Noir'), (1, 2, 'Black'), (2, 1,'Blanc'), (2, 2, 'White'), (3, 1, 'Rouge'), (3, 2, 'Red'), (4, 1, 'Vert'), (4, 2, 'Green'), (5, 1, 'Bleu'), (5, 2, 'Blue'), (6, 1, 'Gris'), 	(6, 2, 'Grey'), (7, 1, 'Brun'), (7, 2, 'Brown'), (8, 1, 'Bourgogne'), (8, 2, 'Burgundy '), (9, 1, 'Bleu Gazon'), (9, 2, 'Turf Blue'), (10, 1, 'Rouge Nintendo'), (10, 2, 'Nintendo Red'), (11, 1, 'Noir Lumineux'), (11, 2, 'Bright Black');

-- -----------------------------------------------------
-- Table `vehicules`.`transmission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`transmission` (
  `id` INT NOT NULL,
  `idLangue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idLangue`)    REFERENCES `vehicules`.`langue` (`id`))
ENGINE = InnoDB;

 

INSERT INTO transmission (id, idLangue, nom) VALUES
                    (1 , 1, 'Manuelle'), (1, 2, 'Manual'), (2, 1, 'Automatique'), (2, 2, 'Automatic ');


 -- -----------------------------------------------------
-- Table `vehicules`.`typeCarrosserie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`typeCarrosserie` (
  `id` INT NOT NULL,
  `idLangue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idLangue`)    REFERENCES `vehicules`.`langue` (`id`))
ENGINE = InnoDB;


INSERT INTO typeCarrosserie (id, idLangue, nom) VALUES
                    (1, 1, 'Berline'), (1, 2, 'Sedan '), (2, 1, 'Coupé'), (2, 2, 'Coupe'), (3, 1, 'Hayon'), (3, 2, 'Hatchback'), (4, 1, 'Familiale'), (4, 2, 'Station wagon'), (5, 1, 'Cabriolet'), (5, 2, 'Convertible '), (6, 1, 'VUS'), (6, 2, 'SUV'), (7, 1, 'Pick-up'), (7, 2, 'Pickup Truck'), (8, 1, 'Mini-fourgonnette'), (8, 2, 'Minivan');                  


-- -----------------------------------------------------
-- Table `vehicules`.`voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`voiture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idModele` INT NOT NULL,
  `idAnnee` INT NOT NULL,
  `kilometrage` INT UNSIGNED NULL,
  `dateArivee` DATE NOT NULL,
  `prixAchat` DECIMAL(15,2) UNSIGNED NOT NULL,
  `prixVente` DECIMAL(15,2) UNSIGNED NOT NULL,
  `idMotopropulseur` INT NOT NULL,
  `idTypeCarburant` INT NOT NULL,
  `idCouleur` INT NOT NULL,
  `idTransmission` INT NOT NULL,
  `idTypeCarrosserie` INT NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  `vna` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `idMotopropulseur`
    FOREIGN KEY (`idMotopropulseur`)
    REFERENCES `vehicules`.`motopropulseur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAnnee`
    FOREIGN KEY (`idAnnee`)
    REFERENCES `vehicules`.`annee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idModele`
    FOREIGN KEY (`idModele`)
    REFERENCES `vehicules`.`modele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTypeCarburant`
    FOREIGN KEY (`idTypeCarburant`)
    REFERENCES `vehicules`.`typeCarburant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCouleur`
    FOREIGN KEY (`idCouleur`)
    REFERENCES `vehicules`.`couleur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTransmission`
    FOREIGN KEY (`idTransmission`)
    REFERENCES `vehicules`.`transmission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTypeCarrosserie`
    FOREIGN KEY (`idTypeCarrosserie`)
    REFERENCES `vehicules`.`typeCarrosserie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO voiture (idModele, idAnnee, kilometrage, dateArivee, prixAchat, prixVente, idMotopropulseur, idTypeCarburant, idCouleur, idTransmission, idTypeCarrosserie, disponibilite, vna) VALUES
                    ( 1, 7, 90873, '2018-10-24', 8538.75, 11385, 1, 1, 2, 2, 2, 1, '1D4GP25B038108775'), 
                    ( 2, 5, 116456, '2018-10-24', 6746.25, 8995, 1, 1, 2, 2, 1, 1, '1D4GP25B038108775'), 
                    ( 3, 6, 65724, '2018-10-27', 8846.25, 11795, 1, 1, 6, 2, 2, 1, '1D4GP25B038108775'), 
                    ( 2, 7, 74573, '2018-10-31', 9120, 12160, 1, 1, 6, 1, 3, 1, '1D4GP25B038108775'),
	( 4, 5, 101243, '2020-11-05', 5996.25, 7995, 1, 1, 1, 2, 2,1, '1D4GP25B038108775'), 
	( 5, 3, 114234, '2021-03-15', 4837.5, 6450, 1, 1, 7, 2, 1, 1, '1D4GP25B038108775'), 
	( 6, 7, 65000, '2021-03-15', 8246.25, 10995, 1, 1, 3, 2, 2, 1, '1D4GP25B038108775'), 
	( 7, 6, 107585, '2021-03-15', 7421.25, 9895, 1, 1, 3, 2, 3, 1, '1D4GP25B038108775'), 
	( 6, 6, 100665, '2021-03-15', 7162.5, 9550, 1, 1, 2, 1, 2, 1, '1D4GP25B038108775'), 
	( 8, 7, 51238, '2021-03-15', 9371.25, 12495, 1, 1, 5, 2, 1, 1, '1D4GP25B038108775'), 
	( 9, 5, 86887, '2021-04-15', 7421.25, 9895, 1, 1, 1, 1, 1, 1, '1D4GP25B038108775'), 
	( 10, 7, 94100, '2021-04-15', 11246.2, 14995, 2, 1, 6, 2, 2, 1, '1D4GP25B038108775'), 
	( 3, 6, 65724, '2021-04-15', 8981.25, 11975, 1, 1, 6, 2, 2, 1, '1D4GP25B038108775'), 
	( 11, 6, 104, '2021-04-15', 15963.75, 21285, 1, 2, 2, 1, 2, 1, '1D4GP25B038108775'), 
	( 12, 7, 46201, '2021-04-15', 8437.5, 11250, 1, 1, 6, 2, 3, 1, '1D4GP25B038108775'), 
	( 13, 6, 100599, '2021-01-17', 9637.5, 12850, 2, 1, 1, 2, 6, 1, '1D4GP25B038108775'),
	( 14, 6, 127453, '2021-01-17', 10785, 14380, 2, 2, 6, 1, 6, 1, '1D4GP25B038108775'),
	( 15, 6, 96221, '2021-01-17', 10192.5, 14550, 2, 1, 6, 2, 6, 1, '1D4GP25B038108775'),
	( 16, 7, 116058, '2021-01-17', 19871.25, 26495, 2, 2, 1, 1, 6, 1, '1D4GP25B038108775'),
	( 18, 7, 35622, '2021-01-17', 14246.25, 18995, 1, 1, 6, 2, 6, 1, '1D4GP25B038108775'),
	( 19, 7, 79157, '2021-01-17', 15817.5, 21090, 2, 1, 6, 2, 6, 1, '1D4GP25B038108775'),
	( 20, 7, 119783, '2021-01-17', 13470, 17960, 2, 1, 7, 1, 6, 1, '1D4GP25B038108775'),
	( 17, 9, 69942, '2021-01-17', 15855, 21140, 1, 1, 6, 2, 6, 1, '1D4GP25B038108775'),
	( 21, 7, 84763, '2021-01-17', 12746.25, 16995, 2, 1, 1, 2, 6, 1, '1D4GP25B038108775'),
	( 22, 9, 45436, '2021-01-17', 19511.25, 26015, 2, 1, 2, 2, 6, 1, '1D4GP25B038108775'),
	( 23, 7, 137789, '2021-01-17', 12371.25, 16495, 1, 1, 2, 2, 8, 1, '1D4GP25B038108775'),
	( 24, 8, 103000, '2021-01-17', 13496.25, 17995, 1, 2, 8, 2, 8, 1, '1D4GP25B038108775'),
	( 25, 7, 89049, '2021-01-17', 14572.5, 19430, 2, 1, 2, 2, 8, 1, '1D4GP25B038108775'),
	( 24, 9, 59900, '2021-01-17', 17621.25, 23495, 2, 1, 6, 2, 8, 1, '1D4GP25B038108775'),
	( 23, 11, 50805, '2021-01-17', 19496.25, 25995, 2, 1, 1, 2, 8, 1, '1D4GP25B038108775'),
	( 26, 6, 133896, '2021-01-17', 14208.75, 18945, 1, 1, 5, 2, 8, 1, '1D4GP25B038108775'),
	( 27, 2, 141461, '2021-01-17', 5962.5, 7950, 1, 2, 6, 1, 8, 1, '1D4GP25B038108775'),
	( 26, 11, 35902, '2021-01-17', 22871.25, 30495, 2, 1, 1, 2, 8, 1, '1D4GP25B038108775'),
	( 28, 10, 53334, '2021-01-17', 56246.25, 74995, 2, 2, 1, 2, 7, 1, '1D4GP25B038108775'),
	( 29, 10, 31935, '2021-01-17', 35212.5, 46950, 2, 2, 1, 2, 7, 1, '1D4GP25B038108775'),
	( 30, 11, 1016, '2021-01-17', 47925, 63900, 2, 2, 2, 2, 7, 1, '1D4GP25B038108775'),
	( 28, 9, 9409, '2021-01-17', 35100, 46800, 2, 2, 2, 1, 7, 1, '1D4GP25B038108775'),
	( 31, 5, 99583, '2021-01-17', 29996.25, 39995, 2, 2, 2, 2, 7, 1, '1D4GP25B038108775'),
	( 32, 9, 81926, '2021-01-17', 52496.25, 69995, 2, 2, 1, 2, 7, 1, '1D4GP25B038108775'),
	( 33, 10, 50235, '2021-01-17', 29246.25, 38995, 2, 2, 3, 2, 7, 1, '1D4GP25B038108775');

-- -----------------------------------------------------
-- Table `vehicules`.`description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`description` (
  `id` INT NOT NULL,
  `idLangue` INT NOT NULL,
  `nom` TEXT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idLangue`)
  REFERENCES `vehicules`.`langue` (`id`),
  FOREIGN KEY (`id`)
  REFERENCES `vehicules`.`voiture` (`id`))
ENGINE = InnoDB;
			

INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (1, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (1, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (2, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (2, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (3, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (3, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (4, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (4, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (5, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (5, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (6, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (6, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (7, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (7, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (8, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (8, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (9, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (9, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (10, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (10, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (11, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (11, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (12, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (12, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (13, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (13, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (14, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (14, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (15, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (15, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (16, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (16, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (17, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (17, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (18, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (18, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (19, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (19, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (20, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (20, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (21, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (21, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (22, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (22, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (23, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (23, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (24, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (24, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (25, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (25, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (26, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (26, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (27, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (27, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (28, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (28, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (29, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (29, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (30, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (30, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (31, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (31, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (32, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (32, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (33, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (33, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (34, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (34, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (35, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (35, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (36, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (36, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (37, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (37, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (38, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (38, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (39, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (39, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (40, 1, 'Selon les articles 159 et 160 de la Loi sur la protection du consommateur, (1978,c9) cette automobile fait partie de la catégorie ci-dessous et comporte une garantie de bon fonctionnement pour le terme ou le kilométrage ci-après indiqué, selon le premier terme atteint: C - 1 mois ou 1,700 km'); 
INSERT INTO `description` (`id`, `idLangue`, `nom`) VALUES (40, 2, 'According to articles 159 and 160 of the Consumer Protection Act, (1978, c9) this automobile is part of the category below and carries a warranty of good working order for the term or the mileage indicated below, according to the first term reached: C - 1 month or 1,700 km'); 

-- -----------------------------------------------------
-- Table `vehicules`.`statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`statut` (
  `id` INT NOT NULL,
  `idLangue` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idLangue`)
  REFERENCES `vehicules`.`langue` (`id`))
ENGINE = InnoDB;

INSERT INTO `statut`(`id`, `idLangue`, `nom`) VALUES (1,1,'En attente');
INSERT INTO `statut`(`id`, `idLangue`, `nom`) VALUES (1,2,'Waiting');
INSERT INTO `statut`(`id`, `idLangue`, `nom`) VALUES (2,1,'Réservé');
INSERT INTO `statut`(`id`, `idLangue`, `nom`) VALUES (2,2,'Reserved');
INSERT INTO `statut`(`id`, `idLangue`, `nom`) VALUES (3,1,'Facturé');
INSERT INTO `statut`(`id`, `idLangue`, `nom`) VALUES (3,2,'Charged');

-- -----------------------------------------------------
-- Table `vehicules`.`expedition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`expedition` (
  `id` INT NOT NULL,
  `idLangue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idLangue`)
  REFERENCES `vehicules`.`langue` (`id`))
ENGINE = InnoDB;

INSERT INTO `expedition`(`id`, `idLangue`, `nom`) VALUES (1,1,'Livraison local');
INSERT INTO `expedition`(`id`, `idLangue`, `nom`) VALUES (1,2,'Local delivery');
INSERT INTO `expedition`(`id`, `idLangue`, `nom`) VALUES (2,1,'Ramassage');
INSERT INTO `expedition`(`id`, `idLangue`, `nom`) VALUES (2,2,'Pickup');

-- -----------------------------------------------------
-- Table `vehicules`.`modePaiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`modePaiement` (
  `id` INT NOT NULL,
  `idLangue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `disponibilite` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `idLangue`),
  FOREIGN KEY (`idLangue`)
  REFERENCES `vehicules`.`langue` (`id`))
ENGINE = InnoDB;

INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (1,1,'Argent comptant');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (1,2,'Cash');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (2,1,'Carte de crédit');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (2,2,'Credit card');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (3,1,'Carte de débit');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (3,2,'Debit card');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (4,1,'Virement bancaire');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (4,2,'Bank transfer');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (5,1,'Paypal');
INSERT INTO `modepaiement`(`id`, `idLangue`, `nom`) VALUES (5,2,'Paypal');

-- -----------------------------------------------------
-- Table `vehicules`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`facture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `date` DATE NOT NULL,
  `prixTotal` DECIMAL(15,2) UNSIGNED NOT NULL,
  `quantite` INT UNSIGNED NOT NULL,
  `idStatut` INT NOT NULL,
  `idExpedition` INT NOT NULL,
  `idModePaiement` INT NOT NULL,
  `noAutorisation` VARCHAR(50),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`idClient`)
  REFERENCES `vehicules`.`usager` (`id`),
  FOREIGN KEY (`idStatut`)
  REFERENCES `vehicules`.`statut` (`id`),
  FOREIGN KEY (`idExpedition`)
  REFERENCES `vehicules`.`expedition` (`id`),
  FOREIGN KEY (`idModePaiement`)
  REFERENCES `vehicules`.`modePaiement` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicules`.`listeAchat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`listeAchat` (
  `idCommande` INT NOT NULL,
  `idVoiture` INT NOT NULL,
  `prixVenteFinal` DECIMAL(15,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCommande`, `idVoiture`),
  CONSTRAINT `idCommande`
    FOREIGN KEY (`idCommande`)
    REFERENCES `vehicules`.`facture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVoiture`
    FOREIGN KEY (`idVoiture`)
    REFERENCES `vehicules`.`voiture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicules`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lien` VARCHAR(100) NULL,
  `idVoiture` INT NOT NULL,
  `sort` INT DEFAULT 0,
  PRIMARY KEY (`id`),

    FOREIGN KEY (`idVoiture`)
    REFERENCES `vehicules`.`voiture` (`id`))
ENGINE = InnoDB;

INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (00).jpg', 1 , 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (01).jpg', 1 , 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (02).jpg', 1 , 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (03).jpg', 1 , 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (04).jpg', 1 , 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (05).jpg', 1 , 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (06).jpg', 1 , 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (07).jpg', 1 , 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (08).jpg', 1 , 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (09).jpg', 1 , 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (10).jpg', 1 , 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (11).jpg', 1 , 11);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (12).jpg', 1 , 12);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (13).jpg', 1 , 13);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (14).jpg', 1 , 14);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (15).jpg', 1 , 15);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Cruze-2016 (16).jpg', 1 , 16);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Sentra-2016 (00).jpg', 10 , 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Sentra-2016 (01).jpg', 10, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Sentra-2016 (02).jpg', 10, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Sentra-2016 (03).jpg', 10, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Sentra-2016 (04).jpg', 10, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Sentra-2016 (05).jpg', 10, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Sentra-2016 (06).jpg', 10, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (00).jpg', 11, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (01).jpg', 11, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (02).jpg', 11, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (03).jpg', 11, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (04).jpg', 11, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (05).jpg', 11, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (06).jpg', 11, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (07).jpg', 11, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Jetta-2014 (08).jpg', 11, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (00).jpg', 12, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (01).jpg', 12, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (02).jpg', 12, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (03).jpg', 12, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (04).jpg', 12, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (05).jpg', 12, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (06).jpg', 12, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (07).jpg', 12, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (08).jpg', 12, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Optima-2016 (09).jpg', 12, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (00).jpg', 13, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (01).jpg', 13, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (02).jpg', 13, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (03).jpg', 13, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (04).jpg', 13, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (05).jpg', 13, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (06).jpg', 13, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (07).jpg', 13, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (08).jpg', 13, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mercedes_Benz-CLA250-2015 (00).jpg', 14, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mercedes_Benz-CLA250-2015 (01).jpg', 14, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mercedes_Benz-CLA250-2015 (02).jpg', 14, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mercedes_Benz-CLA250-2015 (03).jpg', 14, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa Note-2017 (00).jpg', 15, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa_Note-2016 (01).jpg', 15, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa_Note-2016 (02).jpg', 15, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa_Note-2016 (03).jpg', 15, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa_Note-2016 (04).jpg', 15, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa_Note-2016 (05).jpg', 15, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa_Note-2016 (06).jpg', 15, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa_Note-2016 (07).jpg', 15, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Versa_Note-2016 (08).jpg', 15, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Compass-2015 (00).jpg', 16, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Compass-2015 (01).jpg', 16, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Compass-2015 (02).jpg', 16, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Compass-2015 (03).jpg', 16, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Compass-2015 (04).jpg', 16, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Compass-2015 (05).jpg', 16, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Compass-2015 (06).jpg', 16, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Compass-2015 (07).jpg', 16, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Escape-2015 (00).jpg', 17, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Escape-2015 (01).jpg', 17, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Escape-2015 (02).jpg', 17, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Escape-2015 (03).jpg', 17, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Escape-2015 (04).jpg', 17, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Escape-2015 (05).jpg', 17, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Escape-2015 (06).jpg', 17, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Escape-2015 (07).jpg', 17, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Rogue-2015 (00).jpg', 18, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Rogue-2015 (01).jpg', 18, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Rogue-2015 (02).jpg', 18, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Rogue-2015 (03).jpg', 18, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Rogue-2015 (04).jpg', 18, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Journey-2016 (00).jpg', 19, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Journey-2016 (01).jpg', 19, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Journey-2016 (02).jpg', 19, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Journey-2016 (03).jpg', 19, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Journey-2016 (04).jpg', 19, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (00).jpg', 2, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (01).jpg', 2, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (02).jpg', 2, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (03).jpg', 2, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (04).jpg', 2, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (05).jpg', 2, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (06).jpg', 2, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (07).jpg', 2, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (08).jpg', 2, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (09).jpg', 2, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (10).jpg', 2, 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (11).jpg', 2, 11);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (12).jpg', 2, 12);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (13).jpg', 2, 13);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (14).jpg', 2, 14);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (15).jpg', 2, 15);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (16).jpg', 2, 16);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (17).jpg', 2, 17);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2014 (18).jpg', 2, 18);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_3-2016 (00).jpg', 20, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_3-2016 (01).jpg', 20, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_3-2016 (02).jpg', 20, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_3-2016 (03).jpg', 20, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_3-2016 (04).jpg', 20, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_3-2016 (05).jpg', 20, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Pathfinder-2016 (00).jpg', 21, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Pathfinder-2016 (01).jpg', 21, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Santa_Fe_Sport-2016 (00).jpg', 22, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Santa_Fe_Sport-2016 (01).jpg', 22, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Santa_Fe_Sport-2016 (02).jpg', 22, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Santa_Fe_Sport-2016 (03).jpg', 22, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Santa_Fe_Sport-2016 (04).jpg', 22, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Santa_Fe_Sport-2016 (05).jpg', 22, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Santa_Fe_Sport-2016 (06).jpg', 22, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Equinox-2018 (00).jpg', 23, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Equinox-2018 (01).jpg', 23, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Equinox-2018 (02).jpg', 23, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Equinox-2018 (03).jpg', 23, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Equinox-2018 (04).jpg', 23, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Chevrolet-Equinox-2018 (05).jpg', 23, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_5-2016 (00).jpg', 24, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_5-2016 (01).jpg', 24, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_5-2016 (02).jpg', 24, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_5-2016 (03).jpg', 24, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_5-2016 (04).jpg', 24, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Mazda-CX_5-2016 (05).jpg', 24, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Rav4-2018 (00).jpg', 25, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Rav4-2018 (01).jpg', 25, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Rav4-2018 (02).jpg', 25, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Rav4-2018 (03).jpg', 25, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Rav4-2018 (04).jpg', 25, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Rav4-2018 (05).jpg', 25, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2016 (00).jpg', 26, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2016 (01).jpg', 26, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2016 (02).jpg', 26, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2016 (03).jpg', 26, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2016 (04).jpg', 26, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Grand_Caravan-2017 (00).jpg', 27, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Grand_Caravan-2017 (01).jpg', 27, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Grand_Caravan-2017 (02).jpg', 27, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Grand_Caravan-2017 (03).jpg', 27, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Odyssey-2016 (00).jpg', 28, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Odyssey-2016 (01).jpg', 28, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Odyssey-2016 (02).jpg', 28, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Odyssey-2016 (03).jpg', 28, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Odyssey-2016 (04).jpg', 28, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Odyssey-2016 (05).jpg', 28, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Grand_Caravan-2018 (00).jpg', 29, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Grand_Caravan-2018 (01).jpg', 29, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Grand_Caravan-2018 (02).jpg', 29, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Dodge-Grand_Caravan-2018 (03).jpg', 29, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (00).jpg', 3, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (01).jpg', 3, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (02).jpg', 3, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (03).jpg', 3, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (04).jpg', 3, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (05).jpg', 3, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (06).jpg', 3, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (07).jpg', 3, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (08).jpg', 3, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (09).jpg', 3, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (10).jpg', 3, 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (11).jpg', 3, 11);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (12).jpg', 3, 12);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (13).jpg', 3, 13);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (14).jpg', 3, 14);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (15).jpg', 3, 15);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Honda-Civic-2015 (16).jpg', 3, 16);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2020 (00).jpg', 30, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2020 (01).jpg', 30, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2020 (02).jpg', 30, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2020 (03).jpg', 30, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2020 (04).jpg', 30, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2020 (05).jpg', 30, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Sedona-2020 (06).jpg', 30, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2015 (00).jpg', 31, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2015 (01).jpg', 31, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2015 (02).jpg', 31, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2015 (03).jpg', 31, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2015 (04).jpg', 31, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2015 (05).jpg', 31, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2015 (06).jpg', 31, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Routan-2011 (00).jpg', 32, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Routan-2011 (01).jpg', 32, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Routan-2011 (02).jpg', 32, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Routan-2011 (03).jpg', 32, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Volkswagen-Routan-2011 (04).jpg', 32, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2020 (00).jpg', 33, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2020 (01).jpg', 33, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2020 (02).jpg', 33, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2020 (03).jpg', 33, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2020 (04).jpg', 33, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2020 (05).jpg', 33, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Toyota-Sienna-2020 (06).jpg', 33, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2019 (00).jpg', 34, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2019 (01).jpg', 34, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2019 (02).jpg', 34, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2019 (03).jpg', 34, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2019 (04).jpg', 34, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2019 (05).jpg', 34, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2019 (06).jpg', 34, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2019 (07).jpg', 34, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Ranger-2019 (00).jpg', 35, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Ranger-2019 (01).jpg', 35, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Ranger-2019 (02).jpg', 35, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Ranger-2019 (03).jpg', 35, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Ranger-2019 (04).jpg', 35, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Ranger-2019 (05).jpg', 35, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Ranger-2019 (06).jpg', 35, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Gladiator-2020 (00).jpg', 36, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Gladiator-2020 (01).jpg', 36, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Gladiator-2020 (02).jpg', 36, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Gladiator-2020 (03).jpg', 36, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Gladiator-2020 (04).jpg', 36, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Gladiator-2020 (05).jpg', 36, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Jeep-Gladiator-2020 (06).jpg', 36, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2018 (00).jpg', 37, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2018 (01).jpg', 37, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2018 (02).jpg', 37, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2018 (03).jpg', 37, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2018 (04).jpg', 37, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-2500-2018 (05).jpg', 37, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-3500-2014 (00).jpg', 38, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-3500-2014 (01).jpg', 38, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-3500-2014 (02).jpg', 38, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-3500-2014 (03).jpg', 38, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-3500-2014 (04).jpg', 38, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-3500-2014 (05).jpg', 38, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ram-3500-2014 (06).jpg', 38, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Sierra-2018 (00).jpg', 39, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Sierra-2018 (01).jpg', 39, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Sierra-2018 (02).jpg', 39, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Sierra-2018 (03).jpg', 39, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Sierra-2018 (04).jpg', 39, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Sierra-2018 (05).jpg', 39, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Sierra-2018 (06).jpg', 39, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (00).jpg', 4, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (01).jpg', 4, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (02).jpg', 4, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (03).jpg', 4, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (04).jpg', 4, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (05).jpg', 4, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (06).jpg', 4, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (07).jpg', 4, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (08).jpg', 4, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (09).jpg', 4, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (10).jpg', 4, 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (11).jpg', 4, 11);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (12).jpg', 4, 12);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (13).jpg', 4, 13);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (14).jpg', 4, 14);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Ford-Focus-2016 (15).jpg', 4, 15);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (00).jpg', 40, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (01).jpg', 40, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (02).jpg', 40, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (03).jpg', 40, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (04).jpg', 40, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (05).jpg', 40, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (06).jpg', 40, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (07).jpg', 40, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (08).jpg', 40, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (09).jpg', 40, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('GMC-Canyon-2019 (10).jpg', 40, 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Fort.e-2014 (00).jpg', 5, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (01).jpg', 5, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (02).jpg', 5, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (03).jpg', 5, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (04).jpg', 5, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (05).jpg', 5, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (06).jpg', 5, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (07).jpg', 5, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (08).jpg', 5, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (09).jpg', 5, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (10).jpg', 5, 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (11).jpg', 5, 11);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (12).jpg', 5, 12);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (13).jpg', 5, 13);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (14).jpg', 5, 14);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (15).jpg', 5, 15);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Kia-Forte-2014 (16).jpg', 5, 16);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (00).jpg', 6, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (01).jpg', 6, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (02).jpg', 6, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (03).jpg', 6, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (04).jpg', 6, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (05).jpg', 6, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (06).jpg', 6, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (07).jpg', 6, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (08).jpg', 6, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (09).jpg', 6, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (10).jpg', 6, 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (11).jpg', 6, 11);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (12).jpg', 6, 12);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Accent-2012 (13).jpg', 6, 13);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (00).jpg', 7, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (01).jpg', 7, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (02).jpg', 7, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (03).jpg', 7, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (04).jpg', 7, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (05).jpg', 7, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (06).jpg', 7, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (07).jpg', 7, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (08).jpg', 7, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (09).jpg', 7, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (10).jpg', 7, 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (11).jpg', 7, 11);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (12).jpg', 7, 12);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2016 (13).jpg', 7, 13);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (00).jpg', 8, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (01).jpg', 8, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (02).jpg', 8, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (03).jpg', 8, 3);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (04).jpg', 8, 4);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (05).jpg', 8, 5);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (06).jpg', 8, 6);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (07).jpg', 8, 7);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (08).jpg', 8, 8);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (09).jpg', 8, 9);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (10).jpg', 8, 10);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (11).jpg', 8, 11);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (12).jpg', 8, 12);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (13).jpg', 8, 13);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (14).jpg', 8, 14);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Nissan-Micra-2015 (15).jpg', 8, 15);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2015 (00).jpg', 9, 0);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2015 (01).jpg', 9, 1);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2015 (02).jpg', 9, 2);
INSERT INTO `vehicules`.`image`(`lien`,`idVoiture`, `sort`) VALUES ('Hyundai-Elantra-2015 (03).jpg', 9, 3);


-- -----------------------------------------------------
-- Table `vehicules`.`url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicules`.`url` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `query` VARCHAR(100) NOT NULL,
  `motCle` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
